In [1]:
import pandas as pd
import numpy as np

In [4]:
import pandas as pd

carac = pd.read_csv("data/caracteristiques.csv", sep=";")
lieux = pd.read_csv("data/lieux-2024 gd.csv", sep=";")
vehicules = pd.read_csv("data/vehicules-2024 gd.csv", sep=";")
usagers = pd.read_csv("data/usagers-2024 gd.csv", sep=";")

In [13]:
print("carac:", carac.columns.tolist())
print("lieux:", lieux.columns.tolist())
print("vehicules:", vehicules.columns.tolist())
print("usagers:", usagers.columns.tolist())

carac: ['Num_Acc,jour,mois,an,hrmn,lum,dep,com,agg,int,atm,col,adr,lat,long']
lieux: ['Num_Acc,catr,voie,v1,v2,circ,nbv,vosp,prof,pr,pr1,plan,lartpc,larrout,surf,infra,situ,vma']
vehicules: ['Num_Acc,id_vehicule,num_veh,senc,catv,obs,obsm,choc,manv,motor,occutc']
usagers: ['Num_Acc,id_usager,id_vehicule,num_veh,place,catu,grav,sexe,an_nais,trajet,secu1,secu2,secu3,locp,actp,etatp']

In [16]:
for df in [carac, lieux, vehicules, usagers]:
    df.columns = df.columns.str.strip()   
    df.rename(columns=lambda x: x.lower(), inplace=True)

In [24]:
import pandas as pd

carac = pd.read_csv("data/caracteristiques.csv", sep=",")
lieux = pd.read_csv("data/lieux-2024 gd.csv", sep=",")
vehicules = pd.read_csv("data/vehicules-2024 gd.csv", sep=",")
usagers = pd.read_csv("data/usagers-2024 gd.csv", sep=",")

In [25]:
print(carac.columns.tolist())

['Num_Acc', 'jour', 'mois', 'an', 'hrmn', 'lum', 'dep', 'com', 'agg', 'int', 'atm', 'col', 'adr', 'lat', 'long']

In [27]:
print("lieux:", lieux.columns.tolist())

lieux: ['Num_Acc', 'catr', 'voie', 'v1', 'v2', 'circ', 'nbv', 'vosp', 'prof', 'pr', 'pr1', 'plan', 'lartpc', 'larrout', 'surf', 'infra', 'situ', 'vma']

In [28]:
print("vehicules:", vehicules.columns.tolist())

vehicules: ['Num_Acc', 'id_vehicule', 'num_veh', 'senc', 'catv', 'obs', 'obsm', 'choc', 'manv', 'motor', 'occutc']

In [29]:
print("usagers:", usagers.columns.tolist())

usagers: ['Num_Acc', 'id_usager', 'id_vehicule', 'num_veh', 'place', 'catu', 'grav', 'sexe', 'an_nais', 'trajet', 'secu1', 'secu2', 'secu3', 'locp', 'actp', 'etatp']

In [30]:
df = carac.merge(lieux, on="Num_Acc", how="left")
df = df.merge(vehicules, on="Num_Acc", how="left")
df = df.merge(usagers, on="Num_Acc", how="left")

In [31]:
for df in [carac, lieux, vehicules, usagers]:
    df.columns = df.columns.str.strip()  
    df.columns = df.columns.str.replace(" ", "_")  
    df.columns = df.columns.str.lower()

In [32]:
print("carac:", carac.columns.tolist())
print("lieux:", lieux.columns.tolist())
print("vehicules:", vehicules.columns.tolist())
print("usagers:", usagers.columns.tolist())

carac: ['num_acc', 'jour', 'mois', 'an', 'hrmn', 'lum', 'dep', 'com', 'agg', 'int', 'atm', 'col', 'adr', 'lat', 'long']
lieux: ['num_acc', 'catr', 'voie', 'v1', 'v2', 'circ', 'nbv', 'vosp', 'prof', 'pr', 'pr1', 'plan', 'lartpc', 'larrout', 'surf', 'infra', 'situ', 'vma']
vehicules: ['num_acc', 'id_vehicule', 'num_veh', 'senc', 'catv', 'obs', 'obsm', 'choc', 'manv', 'motor', 'occutc']
usagers: ['num_acc', 'id_usager', 'id_vehicule', 'num_veh', 'place', 'catu', 'grav', 'sexe', 'an_nais', 'trajet', 'secu1', 'secu2', 'secu3', 'locp', 'actp', 'etatp']

In [33]:
df = carac.merge(lieux, on="num_acc", how="left")
df = df.merge(vehicules, on="num_acc", how="left")
df = df.merge(usagers, on="num_acc", how="left")

In [37]:
df.replace([-1, " "], np.nan, inplace=True)

,num_acc,jour,mois,an,hrmn,lum,dep,com,agg,int,...,grav,sexe,an_nais,trajet,secu1,secu2,secu3,locp,actp,etatp
0,2.020000e+11,25,3,2024,7:40,2,70,70285,1,1,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Unknown,NaN
1,2.020000e+11,20,3,2024,15:05,1,21,21054,2,3,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Unknown,NaN
2,2.020000e+11,22,3,2024,19:30,2,15,15012,1,1,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Unknown,NaN
3,2.020000e+11,24,3,2024,17:50,1,14,14118,2,3,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Unknown,NaN
4,2.020000e+11,25,3,2024,19:35,5,13,13106,1,3,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Unknown,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
20002,2.020000e+11,10,7,2024,2:05,5,94,94065,2,3,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Unknown,NaN
20003,2.020000e+11,30,11,2024,15:27,1,92,92062,2,1,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Unknown,NaN
20004,2.020000e+11,24,10,2024,20:40,3,29,29068,1,1,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Unknown,NaN
20005,2.020000e+11,30,11,2024,15:40,1,92,92012,2,1,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Unknown,NaN
20006,2.020000e+11,10,7,2024,8:30,1,94,94028,2,1,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Unknown,NaN

In [38]:
df.dropna(subset=["jour", "mois", "an"], inplace=True)

In [39]:
numeric_cols = ["jour", "mois", "an"]
df[numeric_cols] = df[numeric_cols].fillna(0)

In [40]:
categorical_cols = [col for col in df.columns if col not in numeric_cols]
df[categorical_cols] = df[categorical_cols].fillna("Unknown")

In [41]:
df.replace([-1, " "], np.nan, inplace=True)

,num_acc,jour,mois,an,hrmn,lum,dep,com,agg,int,...,grav,sexe,an_nais,trajet,secu1,secu2,secu3,locp,actp,etatp
0,2.020000e+11,25,3,2024,7:40,2,70,70285,1,1,...,Unknown,Unknown,Unknown,Unknown,Unknown,Unknown,Unknown,Unknown,Unknown,Unknown
1,2.020000e+11,20,3,2024,15:05,1,21,21054,2,3,...,Unknown,Unknown,Unknown,Unknown,Unknown,Unknown,Unknown,Unknown,Unknown,Unknown
2,2.020000e+11,22,3,2024,19:30,2,15,15012,1,1,...,Unknown,Unknown,Unknown,Unknown,Unknown,Unknown,Unknown,Unknown,Unknown,Unknown
3,2.020000e+11,24,3,2024,17:50,1,14,14118,2,3,...,Unknown,Unknown,Unknown,Unknown,Unknown,Unknown,Unknown,Unknown,Unknown,Unknown
4,2.020000e+11,25,3,2024,19:35,5,13,13106,1,3,...,Unknown,Unknown,Unknown,Unknown,Unknown,Unknown,Unknown,Unknown,Unknown,Unknown
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
20002,2.020000e+11,10,7,2024,2:05,5,94,94065,2,3,...,Unknown,Unknown,Unknown,Unknown,Unknown,Unknown,Unknown,Unknown,Unknown,Unknown
20003,2.020000e+11,30,11,2024,15:27,1,92,92062,2,1,...,Unknown,Unknown,Unknown,Unknown,Unknown,Unknown,Unknown,Unknown,Unknown,Unknown
20004,2.020000e+11,24,10,2024,20:40,3,29,29068,1,1,...,Unknown,Unknown,Unknown,Unknown,Unknown,Unknown,Unknown,Unknown,Unknown,Unknown
20005,2.020000e+11,30,11,2024,15:40,1,92,92012,2,1,...,Unknown,Unknown,Unknown,Unknown,Unknown,Unknown,Unknown,Unknown,Unknown,Unknown
20006,2.020000e+11,10,7,2024,8:30,1,94,94028,2,1,...,Unknown,Unknown,Unknown,Unknown,Unknown,Unknown,Unknown,Unknown,Unknown,Unknown

In [42]:
df.dropna(subset=["jour", "mois", "an"], inplace=True)

In [43]:
numeric_cols = ["jour", "mois", "an"]
df[numeric_cols] = df[numeric_cols].fillna(0)

In [44]:
categorical_cols = [col for col in df.columns if col not in numeric_cols]
df[categorical_cols] = df[categorical_cols].fillna("Unknown")

In [45]:
df["date"] = pd.to_datetime(
    df["an"].astype(int).astype(str) + "-" +
    df["mois"].astype(int).astype(str) + "-" +
    df["jour"].astype(int).astype(str),
    errors="coerce"
)

df["hrmn"] = pd.to_datetime(df["hrmn"], format="%H%M", errors="coerce").dt.time

In [46]:
severity_map = {1: "Indemne", 2: "Blessé léger", 3: "Blessé hospitalisé", 4: "Tué"}
df["grav"] = df["grav"].map(severity_map)

weather_map = {1: "Normal", 2: "Pluie légère", 3: "Pluie forte", 4: "Neige", 5: "Brouillard"}
df["atm"] = df["atm"].map(weather_map)

In [47]:
df.to_csv("data/accidents_cleaned.csv", index=False)